hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpaper --config ~/.config/hypr/conf/awsm/hyprpaper.conf")
    hl.exec_cmd("wired")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd("~/.config/hypr/hyprland/scripts/onedrive_autostart.sh")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("kdeconnect-indicator")
    hl.exec_cmd("waybar -c $HOME/.config/waybar/conf/awsm/config.jsonc -s $HOME/.config/waybar/conf/awsm/style.css ")
end)
