# background #110613
background_opacity 0.7
shell /bin/zsh
enable_audio_bell no

font_family      family="FiraCode Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto

window_padding_width 5 5

env ZSH_THEME=jbergantine
env NVIM_THEME=catppuccin-macchiato
env TMUX_THEME_MODE=awsm
env SYS_THEME=awsm

include Catppuccin-Frappe.conf
