# background #110613
background_opacity 0.7
shell /bin/zsh
enable_audio_bell no

font_family      family="FiraCode Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto

env ZSH_THEME=jbergantine

include Catppuccin-Frappe.conf
