source-file ~/.config/tmux/_general.conf

# install catppuccin manually:
# $ git clone -b v2.3.0 https://github.com/catppuccin/tmux.git ~/.tmux/plugins/catppuccin/tmux

run ~/.tmux/plugins/catppuccin/tmux/catppuccin.tmux

set -g @catppuccin_flavor 'frappe'
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
