# kitty_mod ctrl+x
enabled_layouts splits

map ctrl+w close_window

# clear
map ctrl+c

# splitting
map ctrl+i launch --location=vsplit --cwd=current
map ctrl+v launch --location=hsplit --cwd=current

# moving
map ctrl+h neighboring_window left
map ctrl+l neighboring_window right
map ctrl+k neighboring_window up
map ctrl+j neighboring_window down

# resizing
map ctrl+shift+h resize_window wider
map ctrl+shift+l resize_window narrower
map ctrl+shift+k resize_window taller
map ctrl+shift+j resize_window shorter

# clipboard
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
