# kitty_mod ctrl+x
enabled_layouts splits
kitty_mod ctrl

map kitty_mod+w close_window

# clear
map ctrl+c

# splitting
map kitty_mod+i launch --location=vsplit --cwd=current
map kitty_mod+v launch --location=hsplit --cwd=current

# moving
map kitty_mod+h neighboring_window left
map kitty_mod+l neighboring_window right
map kitty_mod+k neighboring_window up
map kitty_mod+j neighboring_window down

# resizing
map kitty_mod+shift+h resize_window wider
map kitty_mod+shift+l resize_window narrower
map kitty_mod+shift+k resize_window taller
map kitty_mod+shift+j resize_window shorter

# clipboard
map kitty_mod+shift+c copy_to_clipboard
map kitty_mod+shift+v paste_from_clipboard
