input-field {
    size = 15%, 40px
    halign = center
    position = 0, -119px # 160 / 2 image + 40 / 2 input-field + 2 border_input + 2 border_image + 15 padding
    rounding = 8
    placeholder_text = <span font_style="italic"><b>󰌾 Password</b></span>
    inner_color = rgb(303446)
    outer_color = rgb(c6d0f5)
    outline_thickness = 2
    font_color = rgb(c6d0f5)
    font_family = SpaceMono Nerd Font
    hide_input = false
    fade_on_empty = false
    fail_color = rgb(e67172)
    check_color = rgb(7b9ef0)
    dots_size = 0.2
}

background {
    path = ~/.config/hypr/conf/awsm/wallpapers/1293302-colorized.png
    blur_passes = 2
}

label {
    text = cmd[update:1000] echo $TIME
    halign = center
    font_family = SpaceMono Nerd Font
    color = rgb(c6d0f5)
    font_size = 48
    position = 0, 116 # 160 / 2 image + 48 / 2 label + 2 image-border + 10 padding
}

image {
    halign = center
    path = ~/.config/hypr/conf/awsm/wallpapers/allen.jpg
    size = 160
    rounding = -1
    border_size = 2
    border_color = rgb(303446)
}

general {
    hide_cursor = false
}

animation = fade, 1, 2, linear
